# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Install Dependencies, Lint, Build and Test

on: [push]

env:
  AZURE_WEBAPP_NAME: covid-testcenter    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'bin/'      # set this to the node version to use
  ARTIFACT_NAME: 'web'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build -- --prod
#    - name: Test
#      run: npm test -- --configuration=ci
#    - name: E2E
#      run: npm run e2e -- --configuration=ci
    - name: Upload Website
      uses: actions/upload-artifact@v1
      with:
        name: web
        path: www/
    
  release:
    name: Release to Azure WebApp
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - run: ls ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
